package com.noshitechinc.restaurant.core.designsystem.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class AppColors(
    val primary: Color,
    val onPrimary: Color,
    val primaryPressed: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryPressed: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val background: Color,
    val surface: Color,
    val surfaceVariant: Color,
    val surfacePressed: Color,
    val outline: Color,
    val outlineVariant: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textDisabled: Color,
    val disabledContainer: Color,
    val destructive: Color,
    val onDestructive: Color,
    val destructivePressed: Color,
    val destructiveContainer: Color,
    val onDestructiveContainer: Color,
    val success: Color,
    val successContainer: Color,
    val onSuccessContainer: Color,
    val warning: Color,
    val warningContainer: Color,
    val onWarningContainer: Color,
    val info: Color,
    val infoContainer: Color,
    val onInfoContainer: Color,
    val neutralContainer: Color,
    val onNeutralContainer: Color,
    val focusRing: Color,
    val scrim: Color,
)

val LightAppColors = AppColors(
    primary = Color(0xFFC2410C),
    onPrimary = Color(0xFFFFFFFF),
    primaryPressed = Color(0xFF9A3412),
    primaryContainer = Color(0xFFFFEDD5),
    onPrimaryContainer = Color(0xFF7C2D12),
    secondary = Color(0xFF0F766E),
    onSecondary = Color(0xFFFFFFFF),
    secondaryPressed = Color(0xFF115E59),
    secondaryContainer = Color(0xFFCCFBF1),
    onSecondaryContainer = Color(0xFF134E4A),
    background = Color(0xFFF8F7F5),
    surface = Color(0xFFFFFFFF),
    surfaceVariant = Color(0xFFF1EFEC),
    surfacePressed = Color(0xFFE7E5E4),
    outline = Color(0xFFD6D3D1),
    outlineVariant = Color(0xFFE7E5E4),
    textPrimary = Color(0xFF1C1917),
    textSecondary = Color(0xFF57534E),
    textDisabled = Color(0xFFA8A29E),
    disabledContainer = Color(0xFFE7E5E4),
    destructive = Color(0xFFB91C1C),
    onDestructive = Color(0xFFFFFFFF),
    destructivePressed = Color(0xFF991B1B),
    destructiveContainer = Color(0xFFFEE2E2),
    onDestructiveContainer = Color(0xFF7F1D1D),
    success = Color(0xFF15803D),
    successContainer = Color(0xFFDCFCE7),
    onSuccessContainer = Color(0xFF14532D),
    warning = Color(0xFFB45309),
    warningContainer = Color(0xFFFEF3C7),
    onWarningContainer = Color(0xFF78350F),
    info = Color(0xFF1D4ED8),
    infoContainer = Color(0xFFDBEAFE),
    onInfoContainer = Color(0xFF1E3A8A),
    neutralContainer = Color(0xFFF5F5F4),
    onNeutralContainer = Color(0xFF44403C),
    focusRing = Color(0xFF2563EB),
    scrim = Color(0x99000000),
)
