package com.noshitechinc.restaurant.feature.checkout

data class OverlayActions(
    val onDismiss: () -> Unit,
    val onToggleOption: (ModifierGroup, String) -> Unit,
    val onDraftQuantity: (Int) -> Unit,
    val onDraftNote: (String) -> Unit,
    val onAddToOrder: () -> Unit,
    val onSettlement: (Settlement) -> Unit,
    val onRedeemGiftCard: () -> Unit,
    val onSendPaymentLink: () -> Unit,
    val onGiftField: (GiftField) -> Unit,
    val onGiftDigit: (String) -> Unit,
    val onGiftDelete: () -> Unit,
    val onApplyGiftCard: () -> Unit,
    val onBackToTender: () -> Unit,
    val onBackToOrders: () -> Unit,
    val onStreet: (String) -> Unit = {},
    val onApt: (String) -> Unit = {},
    val onZip: (String) -> Unit = {},
    val onDeliveryNotes: (String) -> Unit = {},
    val onKeepAsPickup: () -> Unit = {},
    val onSaveAddress: () -> Unit = {},
    val onCustomerName: (String) -> Unit = {},
    val onCustomerPhone: (String) -> Unit = {},
    val onSaveCustomer: () -> Unit = {},
    val onContinueGiftCard: () -> Unit = {},
    val onGiftAmountDigit: (String) -> Unit = {},
    val onGiftAmountDigits: (String) -> Unit = {},
    val onGiftAmountDelete: () -> Unit = {},
    val onCity: (String) -> Unit = {},
    val onRegion: (String) -> Unit = {},
    val onOpenPaymentLink: () -> Unit = {},
    val onEditPaymentLink: () -> Unit = {},
    val onSavePaymentLinkDetails: () -> Unit = {},
)
