naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']
complexity:
  LongParameterList:
    functionThreshold: 8
    ignoreDefaultParameters: true
    ignoreAnnotated: ['Composable']
  LongMethod:
    ignoreAnnotated: ['Composable']
style:
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotated: ['Composable']
    excludes: ['**/test/**', '**/androidTest/**', '**/core/designsystem/theme/**', '**/core/designsystem/preview/**']
